name: Merge to main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java version
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: maven

      # Build Code
    - name: Run Unit Tests
      run: mvn clean verify -Daudit -s .github/settings.xml

    - name: Deploy Test Reports
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: test-reports
        folder: impls/target/site/jacoco
        commit-message: ":tada: Test Report for build ${{ github.run_number }} yhjYeay"
        tag: "v${{ github.run_number }}"

    - name: Checkout wiki code
      uses: actions/checkout@v2
      with:
        repository: ${{github.repository}}.wiki
        path: markdown

    - name: Push to wiki
      run: |
        cd markdown
        git config --global user.email "you@example.com"
        git config --global user.name "${{github.workflow}}"
        curl https://raw.githubusercontent.com/cardosov/gh-pages/74ea77d418a3c9227a9f9e892d99e617d05001c1/index.html -o Build-${{ github.run_number }}.md 
        git add .
        git diff-index --quiet HEAD || git commit -m "Add changes" && git push
