name: Merge to main

on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java version
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: maven

      # Build Code
    - name: Run Unit Tests
      run: mvn clean verify -Daudit -s .github/settings.xml

    - name: Deploy Test Reports
      uses: hv-actions/report-archiver@main
      with:
        reporting-branch: 'test-reports'
        lookup-folder: 'target/site/serenity'
        report-index-page: 'index.html'
        commit-message: "Test Report files for build ${{ github.run_number }}"
        tag-name: "v${{ github.run_number }}"
