name: Merge to main

on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java version
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: maven

      # Build Code
    - name: Run Unit Tests
      run: mvn clean verify -Daudit -s .github/settings.xml

    - name: Deploy Test Reports
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: test-reports
        folder: impls/target/site/jacoco
        commit-message: "Test Report files for build ${{ github.run_number }}"
        tag: "v${{ github.run_number }}"

    - name: Reporting
      run: |
        echo "### [Unit Test Report for build ${{ github.run_number }}](https://htmlpreview.github.io/?${{ github.server_url }}/${{ github.repository }}/blob/v${{ github.run_number }}/index.html) :rocket:" >> $GITHUB_STEP_SUMMARY
